name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  config-file:
    required: false
    description: 'Path to the config file'
    default: './.github/approve_config.yml'
  token:
    required: true
    description: 'Repository token'
runs:
  using: 'node12'
  main: 'dist/index.js'
