name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  required_reviewers:
    required: true
    description: 'List of required reviewers (comma separated)'
  token:
    required: true
    description: 'Repository token'
runs:
  using: 'node12'
  main: 'dist/index.js'
