name: 'build-test'

on:
  pull_request:
    types: [assigned, unassigned, opened, reopened, synchronize, review_requested, review_request_removed]
  pull_request_review:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          required_reviewers: 'yuichielectric,rerwinx,dchomh'
          token: ${{ secrets.GITHUB_TOKEN }}
